logging:
  log_level: DEBUG
  show_timestamp: true
general:
  log_readings: false
  loop_time: 5
  max_queue_size: 100
mqtt:
  host: mqtt.thegrays.duckdns.org
  port: 1883
  user: "" 
  password: ""
  keep_alive: 60 
  discovery: false #defaults to false, uncomment to enable home-assistant discovery
  discovery_prefix: homeassistant #change to match with setting of home-assistant
  availability_topic: home-assistant/garage/sensors/availability
  payload_available: online
  payload_not_available: offline
sensors:  
  DHT:
    module: dht
    class: DHT_type      
    scan_interval: 15 
    sensors:
      - type: DHT22
        scan_count: 1
        gpio: 3
        discovery: true
        discovery_topic: /sensor/garage/config
        state_topic:
        discovery_payloads:
          - payload:
            device_class: temperature
            name: garage_temperature
            state_topic:
            unit_of_measurement:
            value_template:
          - payload:
            device_class: humidity
            name: garage_humidity
            state_topic:
            unit_of_measurement:
            value_template:



