logging:
  log_level: INFO
  show_timestamp: true
general:
  log_readings: false
  loop_time: 5
  max_queue_size: 100
mqtt:
  host: mqtt.thegrays.duckdns.org
  port: 1883
  user: "" 
  password: ""
  keep_alive: 60 
  discovery: true
  discovery_prefix: homeassistant #change to match with setting of home-assistant
  availability_topic: home-assistant/garage/sensors/availability
  payload_available: online
  payload_not_available: offline
sensors:  
  DHT:
    module: dht
    class: DHT_type      
    scan_interval: 60 
    sensors:
      - type: DHT22
        scan_count: 1
        gpio: 3
        discovery: true
        state_topic: /sensor/garage/state
        discovery_info:
          - device_class: temperature
            name: garage_temperature
            discovery_topic: /sensor/garage_temp/config
            state_topic: homeassistant/sensor/garage/state
            unit_of_measurement: '°F'
            value_template: '{{ value_json.temperature}}'
          - device_class: humidity
            name: garage_humidity
            discovery_topic: /sensor/garage_humid/config
            state_topic: homeassistant/sensor/garage/state
            unit_of_measurement: '%'
            value_template: '{{ value_json.humidity}}'

              

